# Generated by Django 5.2.8 on 2025-12-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordora', '0004_payment_producerwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quality',
        ),
    ]
