# Generated by Django 5.2.8 on 2025-12-07 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordora', '0005_rename_quantity_orderitem_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
