# Generated by Django 5.2.8 on 2025-12-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordora', '0006_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
